# Generated by Django 5.2 on 2025-05-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=39.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='certification',
            name='yearly_price',
            field=models.DecimalField(decimal_places=2, default=399.0, max_digits=8),
        ),
    ]
