# Generated by Django 5.2 on 2025-04-19 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resources/')),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('image', 'Image')], max_length=50)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='certifications.certification')),
            ],
        ),
    ]
