# Generated by Django 5.2 on 2025-04-21 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='resource_type',
        ),
        migrations.AddField(
            model_name='resource',
            name='created_by_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('quiz', 'Quiz'), ('flashcard', 'Flashcard')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certifications.certification'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
