# Generated by Django 5.2 on 2025-05-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_question_options_question_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='user_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
