# Generated by Django 5.2 on 2025-05-13 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyLogin',
        ),
    ]
