# Generated by Django 5.2 on 2026-03-14 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
